# 服务端口
server:
  port: 8004
# 服务名
spring:
  application:
    name: service-cms
  # 环境设置
  profiles:
    active: dev
    # mysql环境配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.211.128
    port: 6379
    database: 0
    timeout: 1800000
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# mybatis设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/trump/cms/mapper/xml/*.xml

