# 服务端口
server:
  port: 8222
  # 服务名
spring:
  application:
    name: service-gateway
# nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
  #设置路由id
      routes:
      - id: service-acl
  #设置路由的uri   lb://nacos注册服务名称
        uri: lb://service-acl
#设置路由断言,代理servicerId为service-acl的/acl/路径
        predicates:
        - Path=/*/acl/**
#配置service-edu服务
      - id: service-edu
        uri: lb://service-edu
        predicates:
        - Path=/eduservice/**
#配置service-msm服务
      - id: service-msm
        uri: lb://service-msm
        predicates:
        - Path=/edumsm/**
      #vod
      - id: service-vod
        uri: lb://service-vod
        predicates:
        - Path=/eduvod/**
        #ucenter
      - id: service-ucenter
        uri: lb://service-ucenter
        predicates:
        - Path=/*/ucenter/**
      #sta
      - id: service-sta
        uri: lb://service-sta
        predicates:
        - Path=/edusta/**
        #oss
      - id: service-oss
        uri: lb://service-oss
        predicates:
        - Path=/eduoss/**
      #order
      - id: service-order
        uri: lb://service-order
        predicates:
        - Path=/eduorder/**
      #cms
      - id: service-cms
        uri: lb://service-cms
        predicates:
        - Path=/educms/**