# 服务端口
server:
  port: 8001
# 服务名
spring:
  application:
    name: service-edu
  # 环境设置
  profiles:
    active: dev
    # mysql环境配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.128:3306/guli?serverTimezone=Asia/Shanghai
    username: root
    password: root
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# 开启熔断机制
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #设置熔断超时时间，默认1000ms
# mybatis设置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/trump/eduservice/mapper/xml/*.xml
  global-config:
    db-config:
      table-underline: true
# 设置日志级别
#logging:
#  level: info

